### ISSUE TITLE
PARSE_FIELD( ): Support Raw fields and do not parse strings with ERP function modules

### ISSUE THREAD

**Issue by uweku** [sbcgua/mockup_loader#1]
Great tool! When debugging and testing I think I found an issue when parsing fields.
Suggestion (currently breaks your test so I'll have a closer look):

METHOD parse_field.
  DATA l_mask TYPE string.

  CASE is_component-type_kind.
    WHEN 'D'. " Date
      CALL FUNCTION 'CONVERT_DATE_TO_INTERNAL'
        EXPORTING
          date_external            = i_data
          accept_initial_date      = 'X'
        IMPORTING
          date_internal            = e_field
        EXCEPTIONS
          date_external_is_invalid = 1
          OTHERS                   = 2.

```
WHEN 'C'. " Char + convexits
  DESCRIBE FIELD e_field EDIT MASK l_mask.
  IF l_mask IS INITIAL.
    e_field = i_data.
  ELSE.
    SHIFT l_mask LEFT DELETING LEADING '='.
    CALL METHOD me->parse_apply_exit
      EXPORTING
        i_data     = i_data
        i_convexit = l_mask
      IMPORTING
        e_field    = e_field.
  ENDIF.

WHEN 'g'. " String
  e_field = i_data.

WHEN 'P'. " Amount
  FIELD-SYMBOLS <lv_string_char> TYPE clike.
  DATA lr_string TYPE REF TO data.
  DATA lv_strlen TYPE i.
  DATA lv_message TYPE string.
  DATA lv_f TYPE f.
  lv_strlen = strlen( i_data ).
  CREATE DATA lr_string TYPE c LENGTH lv_strlen.
  ASSIGN lr_string->* TO <lv_string_char>.
  <lv_string_char> = i_data.

  TRY.
      e_field = i_data.
    CATCH cx_root.
      CALL FUNCTION 'CHAR_FLTP_CONVERSION'
        EXPORTING
          string             = <lv_string_char>
        IMPORTING
          flstr              = lv_f
        EXCEPTIONS
          exponent_too_big   = 1
          exponent_too_small = 2
          string_not_fltp    = 3
          too_many_decim     = 4
          OTHERS             = 5.
      e_field = lv_f.
      IF sy-subrc <> 0.
        MESSAGE ID sy-msgid TYPE sy-msgty NUMBER sy-msgno WITH sy-msgv1 sy-msgv2 sy-msgv3 sy-msgv4 INTO lv_message.
        zcx_mockup_loader_error=>raise(
          EXPORTING
            msg  = lv_message
        ).
      ENDIF.
  ENDTRY.
WHEN 'N' OR 'I'. " Integer number
  IF i_data CO '0123456789'.
    e_field = i_data.
  ELSE.
    sy-subrc = 4.
  ENDIF.
WHEN 'X'."Raw
  e_field = i_data.
```

  ENDCASE.

  IF sy-subrc IS NOT INITIAL.
    zcx_mockup_loader_error=>raise( msg = |Field: { is_component-name }| code = 'PF' ). "#EC NOTEXT
  ENDIF.

ENDMETHOD.

**Comment by sbcgua** [comment]
Hi Uwe,

Thanks for your comment.
1. Added raw data type support
2. Amount parsing. It seems that `CHAR_FLTP_CONVERSION` does not support thousand separators well. Still I decided to refactor parsing a bit and it appeared to be one of those tasks which intended to finish in 10 minutes and end up in half a day ;)
   So now there is a method `class_set_param` to specify separators if needed (see reference.md). The parser is more universal and validates an input with regex (seems that I invented a bicycle but I didn't find a FM that does what I wanted :)

P.S. Both changes are currently in a separate brach - `0.1.4beta` - because I'm not yet sure in it's stability. But you can check anyway.

**Comment by uweku** [comment]
Thanks, I already had a look. Making the seperator configurable is far better than assuming a fixed one for the output. Thanks a lot!
By The way: I updated some testcases to prepare them for SAP systems with non-ERP installations (replace BSET and BKPF structures by SCARR and SFLIGHT)

---
- STORE RETRIEVE types checking test
  
  ---
  
  METHOD retrieve_types.
    DATA:
          lo_ex     TYPE REF TO zcx_mockup_loader_error,
          l_src     TYPE scarr_tab,
          l_dst_tab TYPE scarr_tab,
          l_dst_tt  TYPE TABLE OF scarr,
          l_dst_ts  TYPE SORTED TABLE OF scarr WITH UNIQUE KEY carrid,
          l_dst_str TYPE sflight,
          l_dst_dif TYPE TABLE OF sflight.
  
    APPEND INITIAL LINE TO l_src.
    TRY.
        mo_sut->store( i_name = 'DATA' i_data = l_src ).
      CATCH zcx_mockup_loader_error INTO lo_ex.
        fail( lo_ex->get_text( ) ).
    ENDTRY.
  
    " Store to different kinds of same table *******************
    TRY.
        CALL METHOD mo_sut->_retrieve
          EXPORTING
            i_name = 'DATA'
          IMPORTING
            e_data = l_dst_tab.
        CALL METHOD mo_sut->_retrieve
          EXPORTING
            i_name = 'DATA'
          IMPORTING
            e_data = l_dst_tt.
        CALL METHOD mo_sut->_retrieve
          EXPORTING
            i_name = 'DATA'
          IMPORTING
            e_data = l_dst_ts.
      CATCH zcx_mockup_loader_error INTO lo_ex.
        fail( lo_ex->get_text( ) ).
    ENDTRY.
  
    " Store to structure ***************************************
    TRY.
        CALL METHOD mo_sut->_retrieve
          EXPORTING
            i_name = 'DATA'
          IMPORTING
            e_data = l_dst_str.
      CATCH zcx_mockup_loader_error INTO lo_ex.
    ENDTRY.
  
    assert_not_initial( act = lo_ex ).
    assert_equals( exp = 'TT' act = lo_ex->code ).
  
    " Store to table with different structure ******************
    CLEAR lo_ex.
    TRY.
        CALL METHOD mo_sut->_retrieve
          EXPORTING
            i_name = 'DATA'
          IMPORTING
            e_data = l_dst_dif.
      CATCH zcx_mockup_loader_error INTO lo_ex.
    ENDTRY.
  
    assert_not_initial( act = lo_ex ).
    assert_equals( exp = 'TS' act = lo_ex->code ).
  
  ENDMETHOD.       "retrieve_types

---
- STORE RETRIEVE with table key and sieving (filtering)
  
  ---
  
  METHOD store_retrieve_with_key.
    DATA:
          dummy_exp      TYPE ty_dummy,
          dummy_tab_exp  TYPE tt_dummy,
          dummy_act      TYPE ty_dummy,
          dummy_tab_act  TYPE tt_dummy,
          ls_sflight        TYPE sflight,
          lo_ex          TYPE REF TO zcx_mockup_loader_error.
  
    CALL METHOD get_dummy_data
      IMPORTING
        e_dummy_struc = dummy_exp
        e_dummy_tab   = dummy_tab_exp.
  
    TRY.
        mo_sut->store( i_name = 'TAB' i_data = dummy_tab_exp i_tabkey = 'TNUMBER' ).
      CATCH zcx_mockup_loader_error INTO lo_ex.
        fail( lo_ex->get_text( ) ).
    ENDTRY.
  
    DELETE dummy_tab_exp INDEX 1.
  
    " Positive *****************************************
    TRY.
        CALL METHOD mo_sut->_retrieve
          EXPORTING
            i_name = 'TAB'
            i_sift = '2015'
          IMPORTING
            e_data = dummy_act.
  
  ```
    CALL METHOD mo_sut->_retrieve
      EXPORTING
        i_name = 'TAB'
        i_sift = '2016'
      IMPORTING
        e_data = dummy_tab_act.
  
  CATCH zcx_mockup_loader_error INTO lo_ex.
    fail( lo_ex->get_text( ) ).
  ```
  
    ENDTRY.
  
    assert_equals( act = dummy_act      exp = dummy_exp ).
    assert_equals( act = dummy_tab_act  exp = dummy_tab_exp ).
  
    " Retrieve to wrong structure **********************
    CLEAR lo_ex.
    TRY.
        CALL METHOD mo_sut->_retrieve
          EXPORTING
            i_name = 'TAB'
            i_sift = '2015'
          IMPORTING
            e_data = ls_sflight.
      CATCH zcx_mockup_loader_error INTO lo_ex.
    ENDTRY.
  
    assert_not_initial( act = lo_ex ).
    assert_equals( exp = 'TS' act = lo_ex->code ).
  
    " Retrieve - no data selected **********************
    CLEAR lo_ex.
    TRY.
        CALL METHOD mo_sut->_retrieve
          EXPORTING
            i_name = 'TAB'
            i_sift = '2000'
          IMPORTING
            e_data = dummy_tab_act. " Table
      CATCH zcx_mockup_loader_error INTO lo_ex.
    ENDTRY.
  
    assert_not_initial( act = lo_ex ).
    assert_equals( exp = '04' act = lo_ex->code ).
  
    CLEAR lo_ex.
    TRY.
        CALL METHOD mo_sut->_retrieve
          EXPORTING
            i_name = 'TAB'
            i_sift = '2000'
          IMPORTING
            e_data = dummy_act.    " Structure
      CATCH zcx_mockup_loader_error INTO lo_ex.
    ENDTRY.
  
    assert_not_initial( act = lo_ex ).
    assert_equals( exp = '04' act = lo_ex->code ).
  
    " Save structure ************************************
    CLEAR lo_ex.
    TRY.
        mo_sut->store( i_name = 'STRUC' i_data = dummy_exp i_tabkey = 'TNUMBER' ).
      CATCH zcx_mockup_loader_error INTO lo_ex.
    ENDTRY.
  
    assert_not_initial( act = lo_ex ).
    assert_equals( exp = 'TO' act = lo_ex->code ).
  
    " Tab key that does not exist in the structure ******
    CLEAR lo_ex.
    TRY.
        mo_sut->store( i_name = 'TAB' i_data = dummy_tab_exp i_tabkey = 'UNDEFINED' ).
      CATCH zcx_mockup_loader_error INTO lo_ex.
    ENDTRY.
  
    assert_not_initial( act = lo_ex ).
    assert_equals( exp = 'FM' act = lo_ex->code ).
  
  ENDMETHOD.       "store_retrieve_with_key

**Comment by sbcgua** [comment]
non-ERP tables: That's a good idea. Didn't think from such a perspective. Thanks ! :) 
(adjusted but not yet published ... playing with ZAKE ;)
