### ISSUE TITLE
Double quote issue

### ISSUE THREAD

**Issue by pacroy** [sbcgua/mockup_loader#6]
Method parse_line fails when the field value is double-quoted (e.g. "1,234.56").
Suggested to fix by adding this code at line 1006 in zcl_mockup_loader.abap

`*   Remove double quotes "..."`  
`    data: lv_tmp   type string,`  
`          lv_regex type string.`  
`    lv_regex = '(["]).+\1'.                                    "#ec notext`  
`    lv_tmp = ls_field.`  
`    find all occurrences of regex lv_regex in lv_tmp match count sy-tabix.`  
`    if sy-tabix = 1.`  
`      shift ls_field left deleting leading '"'.`  
`      shift ls_field right deleting trailing '"'.`  
`    endif.`  
`    clear sy-subrc.`

**Comment by sbcgua** [comment]
Thanks for the issue. :)
Do you mean any field can be quoted or number only ?

**Comment by sbcgua** [comment]
Have a look at `PARSE_FIELD` method. Should work now. 

P.S. I finally did what I planned for some time already - migrated to abapGit tool. So the folder structure has changed a bit. The code now in `/src/zcl_mockup_loader.clas.abap`

**Comment by pacroy** [comment]
Thank you for fixing. As I observed, double quotes are added to the field containing comma both numeric and character fields. Save as tab limitted txt with Excel 2013.

PS: abapGit sounds interesting. I'm finding a tool to help syncing ABAP with Git.

**Comment by sbcgua** [comment]
No prob :) OK, I'll close the issue for now. If any other issue, pls open a new one.

P.S. Yeah, have a look at it, it is a great tool - https://github.com/larshp/abapGit/
