### ISSUE TITLE
Custom date format

### ISSUE THREAD

**Issue by pacroy** [sbcgua/mockup_loader#8]
Will get the error "Critical Assertion Error: '[PARSE_FIELD] Field: FLDATE'" when the user's default date format is not matched with the date format in the imported file.

Suggest to add a feature to set custom date format in method CLASS_SET_PARAMS.

**Comment by sbcgua** [comment]
hmm, good idea ... But what kind of format do you have ? I think it would be difficult to implement "all possible kinds" of formats.
One question: how do you create CSV ? With the VB script from repo or manual save ?

**Comment by pacroy** [comment]
Totally understand that. I've tried to find a way to convert from external date in specific format but still found no way. SET COUNTRY command seem not to work.

In your test data file, the date format is DD.MM.YYYY but when I exported from my Excel, the format is MM.DD.YYYY so I have to switch back and forth and re-login if I want to pass all tests.

**Comment by sbcgua** [comment]
Check this branch: https://github.com/sbcgua/mockup_loader/tree/custom-date-parsing

`CLASS_SET_PARAMS` has a new param now which accepts `DMY`, `MDY` or `YMD`.
This is a draft but should be stable.

**Comment by pacroy** [comment]
I got error '[PARSE_DATE] Incorrect date length'. My date field looks like these M/D/YYYY e.g. "1/10/2017" or "1/9/2017" where M and D can be 1 or 2 digit.

**Comment by sbcgua** [comment]
Hmm, i see ...
Well, I can fix it but after 8th of May only - i'm out of my working env currently :)
Probably it will need the separator to be specified. Like `D/M/Y`. To expect certain kind of separator at variable position.

**Comment by pacroy** [comment]
No problem. Enjoy your time!

**Comment by sbcgua** [comment]
@pacroy could you pls try again ?
params format now presumes separator at the end - `.` or `-` or `/`. E.g. `DMY.` which would parse `1.2.2017` and `01.02.2017`.
format without separator (e.g. `DMY`) assumes strict 8-char date without separators

**Comment by sbcgua** [comment]
Just for the note: performance of old (native) and new (custom) approach. I expected a lot worse ... but it seems to be OK (test 10k times)

![image](https://cloud.githubusercontent.com/assets/15635498/26013004/2ccedc3a-375f-11e7-9c7a-b75faefac638.png)

**Comment by pacroy** [comment]
Tested and it works great. Good work! 👍

**Comment by sbcgua** [comment]
:) 
Good. I'll merge it to master this week a bit later then.
Probably will also do some rearrangements with parser. Because in fact I separated it into independednt [repo](https://github.com/sbcgua/abap_data_parser) some time ago and now it is very inconvenient to do changes in both :) I'll probably include the parser as local class.
